name: Deploy Hugo to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
#    runs-on: ubuntu-20.04
    runs-on: windows-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v2
        with:
          submodules: true  # 确保拉取子模块
          fetch-depth: 0  # 拉取所有提交记录，包括分支合并记录

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
#          hugo-version: "latest" # 可以修改为你使用的 Hugo 版本
          hugo-version: "0.144.1" #
          extended: true # 设置是否需要 extended 版本



      - name: Build
        run: hugo --buildDrafts

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }} # 另外还支持 deploy_token 和 github_token
          external_repository: zebin-code/zebin-code.github.io # 修改为你的 GitHub Pages 仓库
          publish_dir: ./public
#          keep_files: false
          publish_branch: main
       
